#!/usr/bin/env python
# ------------------------------------------------------------------------
# janix-sendgrid
# ------------------------------------------------------------------------
import sendgrid
import os
from sendgrid.helpers.mail import *
import getopt
import sys
import pprint

sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))

opts, args = getopt.getopt(sys.argv[1:], "vs:", ["verbose", "subject="])

subject = "email from janixgrid"
verbose = False

for o, a in opts:
    if o in ("-s", "--subject"):
        subject = a
    elif o in ("-v", "--verbose"):
        verbose = True

lines = ""
for line in sys.stdin.readlines():
    lines = lines + line

from_email = Email("janixgrid@janixsoft.com")
content = Content("text/plain", lines )

for addressee in args:
    to_email = Email(addressee)
    mail = Mail(from_email, subject, to_email, content)
    response = sg.client.mail.send.post(request_body=mail.get())

    if verbose:
        print(response.status_code)
        print(response.body)
        print(response.headers)

# ------------------------------------------------------------------------
# END OF SCRIPT
# ------------------------------------------------------------------------
